package com.steiner.make_a_orm.aggregate;

import com.steiner.make_a_orm.IToSQL;
import com.steiner.make_a_orm.column.Column;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;

public abstract class Aggregate<R> implements IToSQL {
    @Nonnull
    public Column<?> column;

    public Aggregate(@Nonnull Column<?> column) {
        this.column = column;
    }

    @Nonnull
    public abstract String alias();

    @Nullable
    public abstract R read(@Nonnull ResultSet resultSet) throws SQLException;


    // generated by wizard
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Aggregate<?> aggregate = (Aggregate<?>) o;
        return Objects.equals(column, aggregate.column);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(column);
    }
}
